import { getTableConfig } from "drizzle-orm/sqlite-core";

import * as schema from "../schema";
import snapshot from "./pg-schema.snapshot.json";

/*
  The two schemas have to agree, column for column.

  db/schema.ts in the web repo and src/data/schema.ts here are hand written, in
  two dialects, in two repositories, and the sync protocol assumes they describe
  the same rows. A drift is not a crash: it is a 400 from the API three weeks
  later, or a column that silently never syncs.

  The Postgres side is a COMMITTED snapshot, generated by
  scripts/emit-schema-snapshot.ts over there. So this runs on a clean clone with
  no access to that repository, and drift shows up either as this test failing
  or as a dirty snapshot after regenerating - both loud.

  The comparison is SEMANTIC. A serial and an integer primary key are the same
  thing; a timestamptz and an integer holding epoch milliseconds are the same
  thing. Both sides normalise to six kinds, which makes spec section 2.1's
  mapping table machine checked rather than a paragraph of prose.

  THE ALLOW LIST IS THE POINT. Anything that differs and is NOT declared below
  fails. That inversion is what makes this survive a redesign: a new column on
  one side is a failure until somebody says, in writing, why it belongs to one
  side only.
*/

type Kind = "int" | "real" | "text" | "bool" | "instant" | "enum";
type ColumnDescriptor = {
  kind: Kind;
  notNull: boolean;
  primaryKey: boolean;
  hasDefault: boolean;
  values?: string[];
};

function kindOf(column: any): Kind {
  const columnType: string = column.columnType ?? "";
  /* Before dataType, which calls both integers and reals "number". ease and
     intervalDays are real on both sides and an int/real mixup is exactly what
     the fold would carry silently. */
  if (/Real|Double/.test(columnType)) return "real";
  if (Array.isArray(column.enumValues) && column.enumValues.length > 0) return "enum";
  switch (column.dataType) {
    case "date":
      return "instant";
    case "boolean":
      return "bool";
    case "number":
      return "int";
    default:
      return "text";
  }
}

function describeColumn(column: any): ColumnDescriptor {
  const descriptor: ColumnDescriptor = {
    kind: kindOf(column),
    notNull: Boolean(column.notNull),
    primaryKey: Boolean(column.primary),
    hasDefault: Boolean(column.hasDefault),
  };
  if (descriptor.kind === "enum") descriptor.values = [...(column.enumValues as string[])].sort();
  return descriptor;
}
function describeSqlite(): Record<string, Record<string, ColumnDescriptor>> {
  const tables: Record<string, Record<string, ColumnDescriptor>> = {};
  for (const value of Object.values(schema)) {
    let config;
    try {
      config = getTableConfig(value as never);
    } catch {
      continue;
    }
    if (!config?.name) continue;
    const columns: Record<string, ColumnDescriptor> = {};
    for (const column of config.columns) columns[column.name] = describeColumn(column);
    tables[config.name] = columns;
  }
  return tables;
}

/*
  Declared divergences. Each one cites why it exists.

  A table named here is expected to be missing from the other side. A column
  named here is expected to be missing from the other side, or to differ in the
  named field. Everything else must match.
*/
const TABLE_ONLY_IN_PG: Record<string, string> = {
  /* The web app still sends web push; the phone schedules its own local
     notifications and has no push server at all (spec section 8). */
  push_subscriptions: "web push only, spec section 8",
};

const TABLE_ONLY_IN_SQLITE: Record<string, string> = {
  /* Local sync bookkeeping. None of it crosses the wire, by design: the cursor
     is opaque and device-owned, and the account row is what lets a cold launch
     resolve a profile without touching the network. */
  device: "device id, minted locally, spec section 4.1",
  account: "the local account row the boot gate reads, spec section 4.1",
  sync_state: "cursor and backoff, device local, spec section 4.4",
  meta: "content version for the seed guard, spec section 5",
};

/* Postgres calls it `profile`, SQLite calls it `profiles`. Same table. */
const TABLE_RENAMES: Record<string, string> = { profile: "profiles" };

/*
  Same column, different name.

  reviews.seq is what the server assigns; reviews.server_seq is where the
  device stores the value it was given back. One concept, and naming them
  apart on the device is deliberate - it reads as "not mine" at every call
  site, which is the point, since writing it from a local clock is exactly the
  way to corrupt a cursor (spec section 4.2).
*/
const COLUMN_RENAMES: Record<string, string> = { "reviews.seq": "server_seq" };

/*
  Columns whose NULLABILITY differs, with the reason.

  All four are the same reason: Postgres carries history the device never had.
  The 118 legacy reviews predate clientId and deviceId, so those columns have
  to be nullable there; every row the device writes carries them, so it can
  require them. A device that relaxed its own constraint to match would be
  throwing away the guarantee the idempotency key exists for.
*/
const NULLABLE_IN_PG_ONLY: Record<string, string> = {
  "reviews.client_id": "legacy rows predate it, spec step A2",
  "reviews.device_id": "legacy rows predate it, spec step A2",
  "card_hearts.device_id": "legacy rows predate it, spec step A2",
  "card_suspensions.device_id": "legacy rows predate it, spec step A2",
};

const COLUMN_ONLY_IN_PG: Record<string, string> = {
  /* The web app keeps PIN auth for its own users; the phone is Clerk only. */
  "profiles.pin_hash": "web PIN login, spec section 4.1",
  "profiles.pin_salt": "web PIN login, spec section 4.1",
  /* Server owned sync bookkeeping. The device is told its cursor, never the
     sequence machinery behind it. */
  "profiles.sync_seq": "server side gapless sequence, spec section 4.2",
  "profiles.deleted_at": "account deletion tombstone; the device is told 410",
  "card_hearts.seq": "server side sequence, spec section 4.2",
  "card_suspensions.seq": "server side sequence, spec section 4.2",
  "card_hearts.created_at": "server bookkeeping; the set is keyed on presence",
  /*
    MIGRATION DEBT, not a design divergence.

    Spec step A1 replaced card_states.suspended with the card_suspensions
    table, and the device has only the table. The web still carries the column
    AND still reads it (lib/stats.ts selects it for the leech list), so it
    cannot simply be dropped - the read sites have to move first. Declared so
    the rest of the check stays useful, and named so it does not become
    invisible.
  */
  "card_states.suspended": "TODO: web has not finished migrating to card_suspensions, spec step A1",
  /*
    The web's old notification dedupe. The phone drops both: with a rolling
    window of one-shot triggers the notification identifiers ARE the dedupe, so
    there is nothing to record (spec section 8).
  */
  "settings.last_notified_on": "web push dedupe, spec section 8",
  "settings.last_notified_hour": "web push dedupe, spec section 8",
};

const COLUMN_ONLY_IN_SQLITE: Record<string, string> = {
  /* Outbox state. The reviews table IS the outbox, so "not yet sent" is a
     column on it rather than a second table (spec section 4.4). */
  "reviews.synced_at": "outbox marker, spec section 4.4",
  /* A row the server permanently rejects is marked and excluded rather than
     retried for ever, which is what kills naive outboxes (spec section 4.4). */
  "reviews.sync_error": "terminal rejection marker, spec section 4.4",
  /*
    Device preferences with no meaning on the web, so they are deliberately
    LOCAL_ONLY in src/sync/engine.ts and never cross the wire.
  */
  "settings.haptics_enabled": "device only, no haptics on the web",
  "settings.reduce_motion": "device only, mirrors an iOS accessibility setting",
  /*
    How to drill on THIS device, not what is scheduled. A phone and a browser
    can reasonably want different answers and neither is a fact about progress,
    so both are LOCAL_ONLY in src/sync/engine.ts and never cross the wire.
  */
  "settings.typing_only": "device only, a preference about the first rung",
  "settings.drill_direction": "device only, filters the queue rather than the schedule",
  /* Per-field last-write-wins needs to know what is unsent and how fresh the
     server's copy was. */
  "settings.dirty": "per-field LWW, spec section 4.3",
  "settings.server_updated_at": "written only from a response, spec section 4.3",
  "card_hearts.dirty": "set sync, spec section 4.3",
  "card_suspensions.dirty": "set sync, spec section 4.3",
};

const keyOf = (table: string, column: string) => `${table}.${column}`;

describe("the two schemas are in lockstep", () => {
  const sqlite = describeSqlite();
  const pg = snapshot.tables as Record<string, Record<string, ColumnDescriptor>>;

  /* Renames applied to the Postgres side, so the rest of the test compares
     like with like. */
  const pgTables: Record<string, Record<string, ColumnDescriptor>> = {};
  for (const [name, columns] of Object.entries(pg)) {
    pgTables[TABLE_RENAMES[name] ?? name] = columns;
  }
  const pgNameFor = (sqliteName: string) =>
    Object.entries(TABLE_RENAMES).find(([, to]) => to === sqliteName)?.[0] ?? sqliteName;

  it("has a snapshot to compare against", () => {
    expect(Object.keys(pg).length).toBeGreaterThan(5);
  });

  it("declares every table that exists on only one side", () => {
    const pgOnly = Object.keys(pgTables).filter((t) => !(t in sqlite));
    const sqliteOnly = Object.keys(sqlite).filter((t) => !(t in pgTables));

    expect(pgOnly.filter((t) => !(pgNameFor(t) in TABLE_ONLY_IN_PG))).toEqual([]);
    expect(sqliteOnly.filter((t) => !(t in TABLE_ONLY_IN_SQLITE))).toEqual([]);
  });

  it("declares every column that exists on only one side", () => {
    const undeclared: string[] = [];

    for (const [table, columns] of Object.entries(pgTables)) {
      if (!(table in sqlite)) continue;
      for (const column of Object.keys(columns)) {
        const renamed = COLUMN_RENAMES[keyOf(table, column)] ?? column;
        if (renamed in sqlite[table]) continue;
        if (keyOf(table, column) in COLUMN_ONLY_IN_PG) continue;
        undeclared.push(`pg only: ${table}.${column}`);
      }
    }

    for (const [table, columns] of Object.entries(sqlite)) {
      if (!(table in pgTables)) continue;
      const renamedFromPg = new Set(
        Object.entries(COLUMN_RENAMES)
          .filter(([from]) => from.startsWith(`${table}.`))
          .map(([, to]) => to),
      );
      for (const column of Object.keys(columns)) {
        if (column in pgTables[table]) continue;
        if (renamedFromPg.has(column)) continue;
        if (keyOf(table, column) in COLUMN_ONLY_IN_SQLITE) continue;
        undeclared.push(`sqlite only: ${table}.${column}`);
      }
    }

    expect(undeclared).toEqual([]);
  });

  /*
    The mapping table from spec section 2.1, checked rather than described.

    hasDefault is deliberately NOT compared: SQLite's defaults are JS side
    ($defaultFn) and Postgres's are SQL side, so the flag means different
    things and comparing it would report a difference on every timestamp.
  */
  it("gives every shared column the same kind and nullability", () => {
    const mismatches: string[] = [];

    for (const [table, columns] of Object.entries(sqlite)) {
      if (!(table in pgTables)) continue;
      for (const [name, sqliteColumn] of Object.entries(columns)) {
        const pgColumn = pgTables[table][name];
        if (!pgColumn) continue;

        if (sqliteColumn.kind !== pgColumn.kind) {
          mismatches.push(`${table}.${name}: sqlite ${sqliteColumn.kind}, pg ${pgColumn.kind}`);
        }
        if (sqliteColumn.notNull !== pgColumn.notNull) {
          const declared =
            keyOf(table, name) in NULLABLE_IN_PG_ONLY &&
            sqliteColumn.notNull &&
            !pgColumn.notNull;
          if (!declared) {
            mismatches.push(
              `${table}.${name}: notNull sqlite ${sqliteColumn.notNull}, pg ${pgColumn.notNull}`,
            );
          }
        }
        if (sqliteColumn.primaryKey !== pgColumn.primaryKey) {
          mismatches.push(`${table}.${name}: primaryKey differs`);
        }
      }
    }

    expect(mismatches).toEqual([]);
  });

  /* An enum that gains a value on one side only is the quiet version of this
     whole failure mode: rows written with it are rejected by the other. */
  it("gives every shared enum the same values", () => {
    const mismatches: string[] = [];

    for (const [table, columns] of Object.entries(sqlite)) {
      if (!(table in pgTables)) continue;
      for (const [name, sqliteColumn] of Object.entries(columns)) {
        const pgColumn = pgTables[table][name];
        if (!pgColumn || sqliteColumn.kind !== "enum" || pgColumn.kind !== "enum") continue;
        if (JSON.stringify(sqliteColumn.values) !== JSON.stringify(pgColumn.values)) {
          mismatches.push(
            `${table}.${name}: sqlite [${sqliteColumn.values}], pg [${pgColumn.values}]`,
          );
        }
      }
    }

    expect(mismatches).toEqual([]);
  });
});
